### ISSUE TITLE
Give img elements an alt attribute.

### ISSUE THREAD

**Issue by josephtkim** [SaraMohamedSamir/prj-rev-bwfs-dasmoto#3]
It is usually a good idea to give image elements alt attributes. These act as placeholder text, descriptions, and also as additional text that search engines can use when finding matches.

https://www.w3schools.com/tags/att_img_alt.asp

**Comment by SaraMohamedSamir** [comment]
Thanks for this information, I will update my code to use alt attribute

**Comment by SaraMohamedSamir** [comment]
new changes have been pushed to the branch with adding alt attribute to the img element
