### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [SaraMohamedSamir/prj-rev-bwfs-dasmoto#7]
**Grade: Meets Expectations**

**Summary:** Great job with your first official project! The page design seems to follow the project spec guidelines closely, which is no small feat taking a given outline and creating a full web page from it. In addition, the code was very well formatted and structured, making it easily readable. I think you are off to a great start for the Intensive Program.

The areas for improvement here are to give each img element an alt attribute to provide descriptions to them, and to give importation sections of the HTML and CSS code descriptions, to make them easier to identify and understand.

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply important web design concepts. You can take a look at these resources to get started - http://getbootstrap.com/ and https://css-tricks.com/snippets/css/a-guide-to-flexbox/. Based on your work so far, I think you are up for the challenge. Keep up the great work!

**Comment by SaraMohamedSamir** [comment]
Thank you so much :)
